// Genre taxonomy and detection constants for CreatorCore campaigns

export const GENRE_TAXONOMY = [
  'Unclassified',
  'Hip-Hop/Rap',
  'Pop',
  'R&B',
  'Country',
  'Rock',
  'Electronic/EDM',
  'Latin',
  'K-Pop',
  'Alternative',
  'Indie',
  'Afrobeats',
  'Reggaeton',
  'Gospel',
  'Folk',
  'Brand',
  'Other',
] as const;

export type Genre = (typeof GENRE_TAXONOMY)[number];

export const GENRE_COLORS: Record<Genre, string> = {
  'Unclassified': '#9CA3AF',
  'Hip-Hop/Rap': '#9333EA',
  'Pop': '#EC4899',
  'R&B': '#F59E0B',
  'Country': '#84CC16',
  'Rock': '#EF4444',
  'Electronic/EDM': '#06B6D4',
  'Latin': '#F97316',
  'K-Pop': '#A855F7',
  'Alternative': '#6366F1',
  'Indie': '#14B8A6',
  'Afrobeats': '#22C55E',
  'Reggaeton': '#FB923C',
  'Gospel': '#FBBF24',
  'Folk': '#A3E635',
  'Brand': '#94A3B8',
  'Other': '#6B7280',
};

// Artist/keyword patterns mapped to genres for heuristic detection.
// Case-insensitive matching is applied at detection time.
// The more keywords here, the fewer Brave Search API calls we need.
export const GENRE_KEYWORDS: Record<string, string[]> = {
  'Hip-Hop/Rap': [
    // Major artists
    'Drake', 'Kendrick Lamar', 'Kendrick', 'Travis Scott', 'J. Cole', 'J Cole',
    'Kanye', 'Ye', 'Jay-Z', 'Jay Z', 'Eminem', 'Nicki Minaj', 'Cardi B',
    'Megan Thee Stallion', 'Post Malone', 'Juice WRLD', 'XXXTentacion',
    'Lil Uzi Vert', 'Lil Baby', 'Lil Wayne', 'Lil Nas X', 'Lil Durk',
    'Lil Pump', 'Lil Yachty', 'Lil Tecca', 'Lil Mosey', 'Lil Tjay',
    'Lil Skies', 'Lil Loaded', 'Lil Keed',
    'Young Thug', 'Young Boy', 'YoungBoy', 'Young Dolph',
    'NBA YoungBoy', 'NBA YB', 'NLE Choppa',
    'DaBaby', 'Pop Smoke', 'Polo G', 'Rod Wave', 'Gunna', 'Future',
    'Metro Boomin', 'Metro', '21 Savage', 'Offset', 'Quavo', 'Takeoff',
    'Migos', 'Playboi Carti', 'A$AP Rocky', 'ASAP Rocky', 'A$AP Ferg',
    'Tyler the Creator', 'Tyler, the Creator', 'Mac Miller', 'Logic',
    'Denzel Curry', 'JID', 'Earthgang', 'Dreamville', 'J.I.D',
    'Pusha T', 'Freddie Gibbs', 'Vince Staples', 'Isaiah Rashad',
    'ScHoolboy Q', 'Ab-Soul', 'Joey Badass', 'Joey Bada$$',
    'Chance the Rapper', 'Childish Gambino', 'Donald Glover',
    'Big Sean', 'Meek Mill', 'Rick Ross', 'Gucci Mane', '2 Chainz',
    'French Montana', 'A Boogie', 'Kodak Black', 'Moneybagg Yo',
    'Key Glock', 'Young Dolph', 'Yo Gotti', 'EST Gee', 'Jack Harlow',
    'Cordae', 'IDK', 'Bas', 'Ari Lennox', 'Rapsody',
    'Ski Mask', 'Smokepurpp', 'Comethazine', 'Trippie Redd',
    'Quando Rondo', 'Yungeen Ace', 'Jackboy', 'Hotboii',
    'Flo Milli', 'GloRilla', 'Glo Rilla', 'Glorilla', 'Latto', 'BIA',
    'Ice Spice', 'Sexyy Red', 'Sexxy Red', 'Doechii',
    'Wiz Khalifa', 'Curren$y', 'Currensy', 'Larry June',
    'Action Bronson', 'Roc Marciano', 'Boldy James', 'Alchemist',
    'Conway the Machine', 'Westside Gunn', 'Benny the Butcher', 'Griselda',
    'Killer Mike', 'Run the Jewels', 'El-P',
    'Lecrae', 'NF', 'Tech N9ne', 'Joyner Lucas', 'Token',
    'Dave East', 'Fabolous', 'Jadakiss', 'Jim Jones', 'Juelz Santana',
    'Busta Rhymes', 'Method Man', 'Redman', 'Ghostface Killah',
    'Raekwon', 'GZA', 'RZA', 'Wu-Tang',
    'Nas', 'Snoop Dogg', 'Dr. Dre', 'Dr Dre', '50 Cent', 'The Game',
    'Ice Cube', 'Too $hort', 'E-40', 'YG', 'Nipsey Hussle',
    'Schoolboy Q', 'Mozzy', 'SOB x RBE',
    'Tyga', 'Blueface', 'Saweetie',
    'Doja Cat', 'Rico Nasty', 'Baby Keem', 'Tee Grizzley',
    '42 Dugg', 'Babyface Ray', 'Veeze', 'Skilla Baby',
    'Yeat', 'Ken Carson', 'Destroy Lonely', 'Homixide Gang',
    'Central Cee', 'Dave', 'Stormzy', 'Skepta', 'AJ Tracey',
    'Headie One', 'Tion Wayne', 'Aitch', 'Digga D',
    'Nardo Wick', 'Finesse2Tymes', 'Tay Keith', 'BigXthaPlug',
    'Bossman Dlow', 'Glorilla', 'Hunxho', 'Rob49',
    'Trap Dickey', 'Tre Loaded', 'Cartel Bo', 'Hustleman',
    'Nino Breeze', 'Mynameisntjmack',
    // Genre keywords
    'Trap', 'Hip Hop', 'Hip-Hop', 'Rap', 'Rapper', 'Bars', 'Flow',
    'Drill', 'Mumble', 'Boom Bap', 'Freestyle', 'Cypher',
  ],

  'Pop': [
    'Taylor Swift', 'Ariana Grande', 'Billie Eilish', 'Dua Lipa',
    'Harry Styles', 'Ed Sheeran', 'Justin Bieber', 'Shawn Mendes',
    'Camila Cabello', 'Selena Gomez', 'Halsey', 'Demi Lovato',
    'Charlie Puth', 'Bebe Rexha', 'Ava Max', 'Anne-Marie',
    'Madison Beer', 'Olivia Rodrigo', 'Sabrina Carpenter', 'Tate McRae',
    'Conan Gray', 'Gracie Abrams', 'Reneé Rapp', 'Renee Rapp',
    'Chappell Roan', 'Addison Rae', 'Nessa Barrett',
    'Doja Cat', 'Lizzo', 'Meghan Trainor', 'Sia',
    'Lady Gaga', 'Katy Perry', 'P!nk', 'Pink', 'Madonna',
    'Britney Spears', 'Christina Aguilera', 'Beyoncé', 'Beyonce',
    'Rihanna', 'Miley Cyrus', 'Lorde', 'Charli XCX', 'Charli xcx',
    'Kim Petras', 'Troye Sivan', 'Tinashe',
    'The Weeknd', 'Bruno Mars', 'Sam Smith', 'Lewis Capaldi',
    'Niall Horan', 'Louis Tomlinson', 'Zayn', 'Liam Payne',
    'Jonas Brothers', 'Joe Jonas', 'Nick Jonas', 'Kevin Jonas',
    'Maroon 5', 'OneRepublic', 'Imagine Dragons', 'AJR',
    'Why Don\'t We', 'PRETTYMUCH', 'CNCO', 'LANY',
    'Bazzi', 'Lauv', 'Jeremy Zucker', 'Chelsea Cutler',
    'Quinn XCII', 'Jon Bellion', 'gnash', 'Alec Benjamin',
    'Alexander 23', 'Stephen Sanchez', 'Benson Boone',
    'Teddy Swims', 'Paul Russell', 'Trevor Daniel',
    'Surfaces', 'AJR', 'WALK THE MOON',
    'Alessia Cara', 'Julia Michaels', 'Lennon Stella',
    'Maisie Peters', 'Holly Humberstone', 'Girl in Red',
    'Tyla', 'Rosalia', 'Rosalía',
    'Joji', 'Rich Brian', '88rising',
    'Melanie Martinez', 'Ashnikko',
    'Khalid', 'Bazzi', 'ROLE MODEL',
    'Lola Young', 'Royel Otis', 'Pretty Savage', 'Olivia Jewel',
    'Sofia Camara',
  ],

  'R&B': [
    'SZA', 'Summer Walker', 'Bryson Tiller', 'Daniel Caesar', 'H.E.R.',
    'Jhené Aiko', 'Jhene Aiko', 'Kehlani', 'Snoh Aalegra',
    'Brent Faiyaz', 'Lucky Daye', 'Giveon', 'Blxst',
    'Ty Dolla $ign', 'Ty Dolla Sign', 'Chris Brown', 'Trey Songz',
    'Usher', 'Ne-Yo', 'Jeremih', 'Omarion', 'Mario',
    'Ella Mai', 'Ari Lennox', 'Chlöe', 'Chloe Bailey', 'Halle Bailey',
    'Chloe x Halle', 'Victoria Monét', 'Victoria Monet',
    'Frank Ocean', 'The Weeknd', 'Miguel', 'Tory Lanez',
    'PartyNextDoor', 'PARTYNEXTDOOR', 'dvsn', 'Majid Jordan',
    '6LACK', 'Sabrina Claudio', 'Kiana Ledé', 'Kiana Lede',
    'Tinashe', 'Teyana Taylor', 'Jazmine Sullivan',
    'Anderson .Paak', 'Anderson Paak', 'Silk Sonic',
    'Steve Lacy', 'Omar Apollo', 'Ravyn Lenae',
    'Jorja Smith', 'Mahalia', 'Joy Crookes',
    'John Legend', 'Alicia Keys', 'Mary J. Blige', 'Erykah Badu',
    'Lauryn Hill', 'D\'Angelo', 'Maxwell', 'Anthony Hamilton',
    'Tank', 'Jacquees', 'Arin Ray', 'Toosii',
    'BLK ODYSSY', 'Ridi', 'Noby', 'Harmless',
    'Kali Uchis', 'Sunshine & Rain',
    // Genre keywords
    'R&B', 'RnB', 'Soul', 'Neo-Soul', 'Neo Soul',
  ],

  'Country': [
    'Morgan Wallen', 'Luke Combs', 'Zach Bryan', 'Bailey Zimmerman',
    'Hardy', 'ERNEST', 'Tyler Childers', 'Chris Stapleton',
    'Jason Aldean', 'Luke Bryan', 'Thomas Rhett', 'Sam Hunt',
    'Dan + Shay', 'Old Dominion', 'Dierks Bentley', 'Brad Paisley',
    'Keith Urban', 'Tim McGraw', 'Kenny Chesney', 'Blake Shelton',
    'Carrie Underwood', 'Miranda Lambert', 'Maren Morris',
    'Kelsea Ballerini', 'Carly Pearce', 'Lainey Wilson',
    'Gabby Barrett', 'Ingrid Andress', 'Priscilla Block',
    'Midland', 'Turnpike Troubadours', 'Flatland Cavalry',
    'Whiskey Myers', 'Brothers Osborne', 'Muscadine Bloodline',
    'Carter Faith', 'Parmalee', 'Russell Dickerson',
    'Dustin Lynch', 'Cole Swindell', 'Riley Green', 'Jordan Davis',
    'Jon Pardi', 'Brett Young', 'Jimmie Allen',
    'Parker McCollum', 'Cody Johnson', 'Jelly Roll',
    'Oliver Anthony', 'Nate Smith', 'Chayce Beckham',
    'Needtobreathe', 'NEEDTOBREATHE', 'Red Clay Strays',
    'Caamp',
    // Genre keywords
    'Country', 'Nashville', 'Bluegrass', 'Honky Tonk',
    'Country Rock', 'Outlaw Country',
  ],

  'Rock': [
    'Foo Fighters', 'Green Day', 'Blink-182', 'blink-182',
    'My Chemical Romance', 'Fall Out Boy', 'Panic! at the Disco',
    'Twenty One Pilots', 'Paramore', 'All Time Low',
    'Bring Me the Horizon', 'A Day to Remember', 'Pierce the Veil',
    'Sleeping with Sirens', 'Of Mice & Men', 'Underoath',
    'The Used', 'Taking Back Sunday', 'Brand New',
    'Metallica', 'Iron Maiden', 'Slipknot', 'Avenged Sevenfold',
    'Ghost', 'Greta Van Fleet', 'The Pretty Reckless',
    'Royal Blood', 'Highly Suspect', 'Nothing But Thieves',
    'Badflower', 'Grandson', 'I Prevail', 'Bad Omens',
    'Polaris', 'Spiritbox', 'Sleep Token',
    'Red Hot Chili Peppers', 'Pearl Jam', 'Soundgarden',
    'Alice in Chains', 'Stone Temple Pilots', 'Nirvana',
    'Linkin Park', 'System of a Down', 'Rage Against the Machine',
    'Tool', 'Deftones', 'Korn', 'Disturbed',
    'Three Days Grace', 'Breaking Benjamin', 'Shinedown',
    'Godsmack', 'Five Finger Death Punch', 'Volbeat',
    'The Offspring', 'Sum 41', 'Simple Plan', 'Good Charlotte',
    'Mayday Parade', 'The Maine', 'Neck Deep', 'State Champs',
    'Waterparks', 'Stand Atlantic', 'Hot Mulligan',
    'AC/DC', 'Led Zeppelin', 'The Rolling Stones', 'The Who',
    'Queen', 'Aerosmith', 'Guns N\' Roses', 'Van Halen',
    'Def Leppard', 'Bon Jovi', 'Journey', 'Foreigner',
    'Ringo Starr', 'Wolf Alice',
    // Genre keywords
    'Rock', 'Metal', 'Punk', 'Hardcore', 'Emo', 'Grunge',
    'Post-Punk', 'Metalcore', 'Deathcore',
  ],

  'Electronic/EDM': [
    'Calvin Harris', 'Marshmello', 'Martin Garrix', 'The Chainsmokers',
    'Kygo', 'Zedd', 'Illenium', 'Said the Sky', 'Dabin',
    'ODESZA', 'Flume', 'Porter Robinson', 'Madeon', 'San Holo',
    'Louis the Child', 'Gryffin', 'NGHTMRE', 'Slander',
    'Excision', 'Rezz', 'Subtronics', 'GRiZ', 'Big Wild',
    'Ekali', 'What So Not', 'RL Grime', 'Baauer', 'Mr. Carmack',
    'Diplo', 'Skrillex', 'DJ Snake', 'Major Lazer',
    'Tiësto', 'Tiesto', 'David Guetta', 'Avicii', 'Swedish House Mafia',
    'Deadmau5', 'deadmau5', 'Eric Prydz', 'Alesso',
    'Nicky Romero', 'Hardwell', 'Afrojack', 'Steve Aoki',
    'Fisher', 'Dom Dolla', 'John Summit', 'Chris Lake',
    'Disclosure', 'Kaytranada', 'Jamie xx', 'Four Tet',
    'Fred again..', 'Fred Again', 'Bicep', 'Rufus Du Sol',
    'Above & Beyond', 'Armin van Buuren', 'Paul van Dyk',
    'Gareth Emery', 'Andrew Rayel', 'Aly & Fila',
    'Anyma', 'Tale of Us', 'Afterlife', 'Artbat',
    'Boris Brejcha', 'Amelie Lens', 'Charlotte de Witte',
    'Nina Kraviz', 'Peggy Gou',
    'TroyBoi', 'Troyboi', 'Sammy Virji',
    'MORTEN', 'Gorgon City',
    // Genre keywords
    'EDM', 'Electronic', 'House', 'Techno', 'Trance', 'Dubstep',
    'Drum and Bass', 'DnB', 'D&B', 'Future Bass', 'Bass House',
    'Deep House', 'Progressive House', 'Electro', 'Synthwave',
    'DJ', 'B2B',
  ],

  'Latin': [
    'Bad Bunny', 'J Balvin', 'Ozuna', 'Daddy Yankee', 'Maluma',
    'Anuel AA', 'Farruko', 'Rauw Alejandro', 'Myke Towers',
    'Sech', 'Lunay', 'Jhay Cortez', 'Feid',
    'Camilo', 'Sebastian Yatra', 'Carlos Vives', 'Juanes',
    'Shakira', 'Enrique Iglesias', 'Ricky Martin', 'Marc Anthony',
    'Romeo Santos', 'Prince Royce', 'Aventura', 'Bachata',
    'Luis Fonsi', 'Nicky Jam', 'De La Ghetto', 'Arcangel',
    'Wisin', 'Yandel', 'Don Omar', 'Tego Calderon',
    'Becky G', 'Karol G', 'Natti Natasha', 'Anitta',
    'Peso Pluma', 'Junior H', 'Natanael Cano', 'Fuerza Regida',
    'Grupo Frontera', 'Grupo Firme', 'Los Tucanes',
    'Christian Nodal', 'Banda MS', 'Calibre 50',
    'Yami Safdie', 'Young Miko',
    // Genre keywords
    'Latin', 'Corrido', 'Corridos', 'Cumbia', 'Salsa', 'Merengue',
    'Bachata', 'Norteño', 'Regional Mexicano', 'Urbano',
    'Musica Mexicana', 'Tumbado',
  ],

  'K-Pop': [
    'BTS', 'BLACKPINK', 'Stray Kids', 'SEVENTEEN', 'ATEEZ',
    'TXT', 'ENHYPEN', 'LE SSERAFIM', 'NewJeans', 'IVE',
    'aespa', 'ITZY', 'NMIXX', '(G)I-DLE', 'GIDLE',
    'TWICE', 'Red Velvet', 'EXO', 'NCT', 'NCT 127', 'NCT Dream',
    'WayV', 'SuperM', 'SHINee', 'Super Junior',
    'GOT7', 'Monsta X', 'iKON', 'TREASURE', 'WINNER',
    'BIGBANG', '2NE1', 'SNSD', 'Girls Generation',
    'MAMAMOO', 'Hwasa', 'Solar', 'Moonbyul',
    'IU', 'Taeyeon', 'Taemin', 'Baekhyun', 'Kai',
    'Jungkook', 'Jimin', 'V', 'SUGA', 'RM',
    'Lisa', 'Jennie', 'Rosé', 'Jisoo',
    'Hyunjin', 'Felix', 'Bang Chan', 'Lee Know',
    'ZEROBASEONE', 'BOYNEXTDOOR', 'RIIZE', 'xikers',
    'Kep1er', 'fromis_9', 'LOONA', 'Dreamcatcher',
    'ADORA', 'BIBI', 'Jeon Somi', 'Chung Ha',
    // Genre keywords
    'K-Pop', 'Kpop', 'K Pop', 'Korean',
  ],

  'Alternative': [
    'Radiohead', 'The 1975', 'Arctic Monkeys', 'Tame Impala',
    'Glass Animals', 'alt-J', 'Two Door Cinema Club',
    'The Neighbourhood', 'The Nbhd', 'LANY',
    'Cage the Elephant', 'Portugal. The Man', 'Young the Giant',
    'Foster the People', 'Passion Pit', 'MGMT', 'Empire of the Sun',
    'M83', 'The War on Drugs', 'Vampire Weekend',
    'The Strokes', 'Interpol', 'The National', 'Arcade Fire',
    'LCD Soundsystem', 'Yeah Yeah Yeahs', 'TV on the Radio',
    'The Black Keys', 'Jack White', 'The White Stripes',
    'Gorillaz', 'Blur', 'Oasis', 'Pulp', 'Suede',
    'Muse', 'Biffy Clyro', 'Foals', 'Bastille', 'Florence + the Machine',
    'Hozier', 'Vance Joy', 'Milky Chance', 'Kaleo',
    'Dayglow', 'Wallows', 'Peach Pit', 'Hippo Campus',
    'The Backseat Lovers', 'Mt. Joy', 'Rainbow Kitten Surprise',
    // Genre keywords
    'Alternative', 'Alt Rock', 'Alt-Rock', 'Shoegaze', 'Dream Pop',
    'Post-Rock', 'Art Rock', 'Psychedelic',
  ],

  'Indie': [
    'Bon Iver', 'Fleet Foxes', 'Phoebe Bridgers', 'Boygenius',
    'Julien Baker', 'Lucy Dacus', 'Snail Mail', 'Soccer Mommy',
    'Japanese Breakfast', 'Mitski', 'Clairo', 'beabadoobee',
    'Rex Orange County', 'Still Woozy', 'boy pablo', 'Gus Dapperton',
    'Mac DeMarco', 'Homeshake', 'Mild High Club', 'Khruangbin',
    'Toro y Moi', 'Unknown Mortal Orchestra', 'King Krule',
    'The Tallest Man on Earth', 'Iron & Wine', 'Sufjan Stevens',
    'Elliott Smith', 'Neutral Milk Hotel', 'Built to Spill',
    'Modest Mouse', 'Death Cab for Cutie', 'The Postal Service',
    'Bright Eyes', 'Conor Oberst',
    'The Lumineers', 'Of Monsters and Men', 'Head and the Heart',
    'Lord Huron', 'Caamp', 'Gregory Alan Isakov',
    'Pinegrove', 'Big Thief', 'Waxahatchee', 'Angel Olsen',
    'Adrianne Lenker', 'Weyes Blood', 'Aldous Harding',
    'Courtney Barnett', 'Stella Donnelly', 'Julia Jacklin',
    'Rouri404', 'rouri404', 'Noevdv',
    // Genre keywords
    'Indie', 'Indie Rock', 'Indie Pop', 'Indie Folk', 'Lo-Fi',
    'Bedroom Pop',
  ],

  'Afrobeats': [
    'Burna Boy', 'Wizkid', 'Davido', 'Tiwa Savage', 'Tems',
    'Fireboy DML', 'Rema', 'Omah Lay', 'Asake', 'Ayra Starr',
    'CKay', 'Kizz Daniel', 'Joeboy', 'Ruger', 'BNXN',
    'Patoranking', 'Mr Eazi', 'Yemi Alade', 'Olamide', 'Naira Marley',
    'Shallipopi', 'Seyi Vibez', 'Portable', 'Zinoleesky',
    'Diamond Platnumz', 'Harmonize', 'Rayvanny',
    'Stonebwoy', 'Sarkodie', 'Shatta Wale', 'Black Sherif',
    'Sauti Sol', 'Khaligraph Jones',
    'King Cruff', 'Banx & Ranx',
    // Genre keywords
    'Afrobeats', 'Afrobeat', 'Afropop', 'Afro', 'Amapiano',
    'Afro House', 'Afro Swing', 'Alté',
  ],

  'Reggaeton': [
    'Bad Bunny', 'Daddy Yankee', 'Don Omar', 'Tego Calderon',
    'Wisin y Yandel', 'Zion y Lennox', 'Plan B',
    'Nicky Jam', 'De La Ghetto', 'J Balvin', 'Maluma',
    'Ozuna', 'Anuel AA', 'Farruko', 'Rauw Alejandro',
    'Myke Towers', 'Jhay Cortez', 'Sech', 'Lunay',
    'El Alfa', 'Tokischa', 'Mora', 'Jay Wheeler',
    // Genre keywords
    'Reggaeton', 'Perreo', 'Dembow',
  ],

  'Gospel': [
    'Kirk Franklin', 'Maverick City Music', 'Elevation Worship',
    'Hillsong', 'Bethel Music', 'Lauren Daigle', 'TobyMac',
    'Chris Tomlin', 'Phil Wickham', 'Kari Jobe',
    'Lecrae', 'KB', 'Andy Mineo', 'Trip Lee', 'Tedashii',
    'Tasha Cobbs Leonard', 'Travis Greene', 'Todd Dulaney',
    'Sinach', 'Tim Godfrey', 'Nathaniel Bassey',
    'DOE', 'Koryn Hawthorne', 'Jonathan McReynolds',
    'Israel Houghton', 'William McDowell', 'JJ Hairston',
    // Genre keywords
    'Gospel', 'Worship', 'Christian', 'CCM', 'Praise',
    'Contemporary Christian', 'Church',
  ],

  'Folk': [
    'Mumford & Sons', 'The Avett Brothers', 'The Lumineers',
    'Of Monsters and Men', 'Vance Joy', 'Ben Howard',
    'Hozier', 'Iron & Wine', 'Fleet Foxes', 'Bon Iver',
    'Gregory Alan Isakov', 'The Head and the Heart',
    'The Decemberists', 'The Tallest Man on Earth',
    'Sufjan Stevens', 'Nick Drake', 'Cat Stevens',
    'Joni Mitchell', 'Bob Dylan', 'Leonard Cohen',
    'Simon & Garfunkel', 'Peter Paul and Mary',
    'Woody Guthrie', 'Pete Seeger',
    'The Oh Hellos', 'Mandolin Orange', 'Watchhouse',
    'First Aid Kit', 'The Staves', 'Laura Marling',
    'Noah Kahan', 'Caamp', 'Hailey Whitters',
    // Genre keywords
    'Folk', 'Acoustic', 'Singer-Songwriter', 'Americana',
    'Roots', 'Traditional', 'Bluegrass',
  ],
};

// Brand/product keywords that indicate non-music campaigns
export const BRAND_KEYWORDS: string[] = [
  // Food & Beverage
  'Kelloggs', 'Kellogg', 'Coca-Cola', 'Coca Cola', 'Pepsi', 'PepsiCo',
  'McDonald\'s', 'McDonalds', 'Burger King', 'Wendy\'s', 'Wendys',
  'Taco Bell', 'KFC', 'Chick-fil-A', 'Subway', 'Starbucks', 'Dunkin',
  'Red Bull', 'Monster Energy', 'Gatorade', 'Prime', 'Liquid Death',
  'Doritos', 'Lay\'s', 'Lays', 'Pringles', 'Cheetos', 'Oreo',
  'M&M', 'Skittles', 'Hershey', 'Snickers', 'Reese',
  'Budweiser', 'Bud Light', 'Corona', 'Heineken', 'Modelo',
  'Dutchbros', 'Dutch Bros', 'Celsius', 'C4 Energy', 'C4',

  // Tech
  'Apple', 'Samsung', 'Google', 'Microsoft', 'Amazon', 'Meta',
  'Sony', 'Nintendo', 'Xbox', 'PlayStation', 'Epic Games',
  'Spotify', 'Netflix', 'Disney', 'Hulu', 'HBO', 'Paramount',
  // Note: TikTok, Instagram, Twitter, Snapchat excluded — they appear as platform indicators
  'Adobe', 'Canva', 'Figma',
  'OpenAI', 'ChatGPT', 'Anthropic',
  'Uber', 'Lyft', 'DoorDash', 'Grubhub', 'Instacart',

  // Fashion & Beauty
  'Nike', 'Adidas', 'Puma', 'New Balance', 'Converse', 'Vans',
  'Under Armour', 'Reebok', 'Jordan', 'Yeezy',
  'Gucci', 'Louis Vuitton', 'Prada', 'Versace', 'Balenciaga',
  'Dior', 'Chanel', 'Fendi', 'Burberry', 'Coach',
  'H&M', 'Zara', 'Uniqlo', 'Gap', 'Old Navy',
  'Sephora', 'Ulta', 'MAC', 'Fenty Beauty', 'Glossier',
  'Maybelline', 'L\'Oreal', 'Loreal', 'Olay', 'Neutrogena',
  'CeraVe', 'The Ordinary', 'Drunk Elephant', 'Tatcha',
  'Eva NYC', 'Revlon', 'Estee Lauder',

  // Automotive
  'BMW', 'Mercedes', 'Audi', 'Tesla', 'Toyota', 'Honda',
  'Ford', 'Chevrolet', 'Jeep', 'Porsche', 'Lamborghini', 'Ferrari',
  'Hyundai', 'Kia', 'Nissan', 'Volkswagen', 'Volvo', 'Subaru',

  // Gaming
  'Minecraft', 'Fortnite', 'Roblox', 'Call of Duty', 'COD',
  'Valorant', 'League of Legends', 'LOL', 'Apex Legends',
  'FIFA', 'Madden', 'NBA 2K', 'GTA', 'Elden Ring',
  'Hogwarts Legacy', 'Zelda', 'Mario', 'Pokemon', 'Pokémon',

  // Retail & Lifestyle
  'Walmart', 'Target', 'Costco', 'IKEA', 'Home Depot',
  'Bath & Body Works', 'Yankee Candle', 'Dyson',
  'Shark', 'CryoGlow', 'Bev Core',

  // Telecom
  'AT&T', 'Verizon', 'T-Mobile', 'Sprint',

  // Finance
  'Visa', 'Mastercard', 'PayPal', 'Venmo', 'Cash App',
  'Robinhood', 'Coinbase', 'Binance',

  // Health & Fitness
  'Peloton', 'Lululemon', 'Gymshark', 'Alo Yoga',
  'GNC', 'Optimum Nutrition', 'Celsius',

  // Miscellaneous brand indicators
  'CFS', 'CYZONE', 'Sapphire Moon',
  'SAVE USA', 'Paparazzi',
];
